name: CI

on: push

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.1"
      - run: flutter get pub
      - run: flutter test
